export const loginSuccess ="ADDUSER"
export const loginStart ="LOGIN_START"
export const loginFail ="LOGIN_FAIL"
export const AddProductType= "ADDPRODUCT"
export const sellerRegisData= "SAVEDATA"
export const addOrder= "ADDORDER"
export const AddReqProductType= "ADDREQUEST"
export const ALL_PRODUCTS= "ALL_PRODUCTS"