export const Collections = {
    Shirts: [
      "Dress Shirts",
      "T-Shirts",
      "Polo Shirts",
      "Casual Button-Up Shirts",
      "Flannel Shirts",
      "Henley Shirts",
      "Sweatshirts",
      "Hoodies",
      "Formal Shirts",
    ],
    Pants: [
      "Jeans",
      "Chinos",
      "Formal Pants",
      "Dress Pants",
      "Cargo Pants",
      "Sweatpants",
      "Joggers",
      "Track Pants",
      "Corduroy Pants",
    ],
    top: [
      "Blouses",
      "T-Shirts",
      "Tank Tops",
      "Crop Tops",
      "Sweaters",
      "Cardigans",
      "Hoodies",
      "Peplum Tops",
      "Tunics",
      "Button-Up Shirts",
      "Bodysuits",
      "Off-the-Shoulder Tops",
      "Wrap Tops",
      "Tube Tops",
      "Kimono Tops",
      "Polo Shirts",
      "Camisoles",
      "Cold Shoulder Tops",
      "Cowl Neck Tops",
      "Ruffle Tops",
    ],
    Bottom: [
      "Jeans",
      "Leggings",
      "Trousers",
      "Skirts",
      "Shorts",
      "Culottes",
      "Palazzo Pants",
      "Joggers",
      "Capri Pants",
      "Wide-Leg Pants",
      "Cargo Pants",
      "Pencil Skirts",
      "A-line Skirts",
      "Maxi Skirts",
      "Mini Skirts",
      "Flared Skirts",
      "Denim Skirts",
      "Pleated Skirts",
      "High-Waisted Pants",
      "Harem Pants",
      "jeggings",
    ],
    Sarees: [
      "Silk Sarees",
      "Cotton Sarees",
      "Chiffon Sarees",
      "Georgette Sarees",
      "Banarasi Sarees",
      "Kanjivaram Sarees",
      "Designer Sarees",
      "Bridal Sarees",
      "Linen Sarees",
      "Printed Sarees",
      "Net Sarees",
      "Half-and-Half Sarees",
      "Satin Sarees",
      "Embroidered Sarees",
      "Saree with Blouse Sets",
      "Traditional Sarees",
      "Bollywood Sarees",
      "Party Wear Sarees",
      "Casual Sarees",
      "Lehenga Sarees",
    ],
    Kurtis: [
      "Anarkali Kurti",
      "Straight Cut Kurti",
      "A-Line Kurti",
      "Flared Kurti",
      "Trail Cut Kurti",
      "High-Low Kurti",
      "Kaftan Style Kurti",
      "Shirt Style Kurti",
      "Cape Style Kurti",
      "Dhoti Style Kurti",
      "Front Slit Kurti",
      "Overlay Kurti",
      "Princess Cut Kurti",
      "Tunic Style Kurti",
      "Double Layered Kurti",
      "Coord Kurtis",
    ],
    KidsShirt: [
      "T-Shirts",
      "Polo Shirts",
      "Button-Up Shirts",
      "Graphic Tees",
      "Long Sleeve Shirts",
      "Hoodies",
      "Sweatshirts",
      "Tank Tops",
      "Henley Shirts",
      "Flannel Shirts",
      "Sport Jerseys",
      "Printed Shirts",
      "Casual Shirts",
      "Dress Shirts",
      "Chambray Shirts",
      "Uniform Shirts",
      "Ruffle Tops (for girls)",
      "Peplum Tops (for girls)",
      "Bodysuits (for infants)",
    ],

    kidspants: [
      "Jeans",
      "Leggings",
      "Trousers",
      "Shorts",
      "Cargo Pants",
      "Sweatpants",
      "Joggers",
      "Track Pants",
      "Corduroy Pants",
      "Khaki Pants",
      "Chinos",
      "Capri Pants",
      "Denim Pants",
      "Athletic Pants",
      "Overalls",
      "School Uniform Pants",
      "Printed Pants",
      "Convertible Pants (with zip-off legs)",
      "Dress Pants",
      "Stretch Pants",
    ],
    shorts: [
      "Denim Shorts",
      "Athletic Shorts",
      "Cargo Shorts",
      "Bermuda Shorts",
      "Chino Shorts",
      "Board Shorts",
      "Cotton Shorts",
      "Khaki Shorts",
      "Printed Shorts",
      "Linen Shorts",
      "Track Shorts",
      "Pull-On Shorts",
      "School Uniform Shorts",
      "Sweat Shorts",
      "Jogger Shorts",
      "Running Shorts",
      "Basketball Shorts",
      "Active Shorts",
      "Pleated Shorts",
      "Swim Shorts",
    ],
    GirlsShirts: [
      "T-Shirts",
      "Blouses",
      "Tank Tops",
      "Polo Shirts",
      "Button-Up Shirts",
      "Sweaters",
      "Hoodies",
      "Long Sleeve Shirts",
      "Crop Tops",
      "Graphic Tees",
    ],
    GirlsPants: [
      "Jeans",
      "Leggings",
      "Trousers",
      "Yoga Pants",
      "Culottes",
      "Jeggings",
      "Cargo Pants",
      "Sweatpants",
      "Capri Pants",
      "Palazzo Pants",
    ],

    GirlsShorts: [
      "Denim Shorts",
      "Athletic Shorts",
      "Cargo Shorts",
      "Bermuda Shorts",
      "Chino Shorts",
      "Board Shorts",
      "Cotton Shorts",
      "Khaki Shorts",
      "Printed Shorts",
      "Linen Shorts",
      "Track Shorts",
      "Pull-On Shorts",
      "School Uniform Shorts",
      "Sweat Shorts",
      "Jogger Shorts",
      "Running Shorts",
      "Basketball Shorts",
      "Active Shorts",
      "Pleated Shorts",
      "Swim Shorts",
    ],

    Frock: [
      "A-Line Frocks",
      "Party Frocks",
      "Casual Frocks",
      "Maxi Frocks",
      "Pinafore Frocks",
      "Sundresses",
      "Floral Frocks",
      "Ruffle Frocks",
      "Smocked Frocks",
      "Tiered Frocks",
    ],
    KidsBaniyans: [
      "Cotton Baniyans",
      "Sleeveless Baniyans",
      "Patterned Baniyans",
      "Sports Baniyans",
      "Printed Baniyans",
      "Vest-Style Baniyans",
      "Crew-Neck Baniyans",
      "Ribbed Baniyans",
      "Colored Baniyans",
      "Tank Top Baniyans",
    ],
  kidspair:[
    "Top & Bottom Buddies",
"Mini Outfit Duos",
"Shirt 'n' Slacks Sets",
"Youthful Pairing Picks",
"Tee & Trouser Tandems",
"Young Style Combinations",
"Kids' CoordiCuts Collection",
"Junior Mix & Match",
"Tiny Tops 'n' Bottoms",
"Kid Combo Couture"
  ]
  };

export  const sizeSelected = {
    Shirts: ["S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "Free Size"],
    Pants: [28, 30, 32, 34, 36, 38, 40, 42],
    top: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "Free Size"],
    Bottom: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "Free Size"],
    Sarees: [
      "5.3 meters",
      "5.5 meters",
      "6 meters",
      "6.1 meters",
      "6.2 meters",
      "6.3 meters",
      "6.4 meters",
      "6.5 meters",
      "6.6 meters",
      "6.7 meters",
      "6.8 meters",
      "6.9 meters",
      "7 meters",
      "9 yards",
    ],
    KidsShirt: ["2T", "3T", "4T", "XS", "S", "M", "L", "XL"],
    kidspants: ["2T", "3T", "4T", "XS", "S", "M", "L", "XL"],
    shorts: ["2T", "3T", "4T", "XS", "S", "M", "L", "XL", "XXXXL", "XXXXXL"],
    KidsBaniyans: ["2T", "3T", "4T", "XS", "S", "M", "L", "XL"],
    GirlsShirts: [
      "2T",
      "3T",
      "4T",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "XXXXL",
      "Free Size",
    ],
    GirlsPants: [
      "2T",
      "3T",
      "4T",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "XXXXL",
      "Free Size",
    ],
    GirlsShorts: [
      "2T",
      "3T",
      "4T",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "XXXXL",
      "Free Size",
    ],
    Frock: [
      "2T",
      "3T",
      "4T",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "XXXXL",
      "Free Size",
    ],
    Kurtis: [
      "2T",
      "3T",
      "4T",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "XXXL",
      "XXXXL",
      "Free Size",
    ],
  kidspair: [
    "0/0",
    "16/20",
    "16/16",
    "20/26",
    "20/20",
    "22/32",
    "20/32",
    "28/32",
    "26/36",
    "34/38"
  ],
  };